const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"课题报名",
                        "menuJump":"列表",
                        "tableName":"ketibaoming"
                    }
                ],
                "menu":"课题报名"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"实验室",
                        "menuJump":"列表",
                        "tableName":"shiyanshi"
                    }
                ],
                "menu":"实验室"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"课题查看",
                        "menuJump":"列表",
                        "tableName":"shiyanshiYuyue"
                    }
                ],
                "menu":"课题查看"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"学生",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
